[package]
name = "dracon-persistence"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"] }
dracon-persistence-kit = { path = "../../dracon-libs/tools/crates/dracon-persistence-kit" }

[[bin]]
name = "persistence"
path = "src/bin/persistence.rs"
